spring:
  profiles:
    group:
      "default": "local"
      "dev": "dev, mail, s3"
      "real1": "real-db, mail, real-s3"
      "real2": "real-db, mail, real-s3"

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/techdot_local
    username: sa
    password:
    driver-class-name: org.h2.Driver

  redis:
    host: localhost
    port: 6379

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
cloud:
  aws:
    credentials:
      access-key: test
      secret-key: test
    region:
      static: ap-northeast-2
    stack:
      auto: false
aws:
  s3:
    bucket: cdn.techdot.info


logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor: debug


app:
  host: http://localhost:8080