spring:
  profiles:
    group:
      "default": "local"
      "dev": "dev, mail"
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/techdot-localdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor: debug # trace: sql 내용 분석용


app:
  host: http://localhost:8080