spring:
  profiles:
    group:
      "default": "local, s3"
      "dev": "dev, mail, s3"
      "real1": "real-db, mail, s3"
      "real2": "real-db, mail, s3"

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/techdot_local
    username: sa
    password:
    driver-class-name: org.h2.Driver

  redis:
    host: localhost
    port: 6379

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor: debug # trace: sql 내용 분석용


app:
  host: http://localhost:8080